version: "3.7"
services:
    sqlserver:
        container_name: mssql_todos_test_db
        image: mcr.microsoft.com/mssql/server:2017-CU18-ubuntu-16.04
        environment:
                - SA_PASSWORD=${MSSQL_PASSWD}
                - ACCEPT_EULA=Y
                - MSSQL_PID=developer
                - MSSQL_LCID=1033
                - MSSQL_MEMORY_LIMIT_MB=2048
                - MSSQL_AGENT_ENABLED=true
        ports:
            - ${MSSQL_PORT}:1433
